main_book:
    resource: "@MainBundle/Controller/BookController.php"
    type:     annotation

main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /


NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: "/doc"


api:
    type: rest
    resource: "routing_api.yml"
    