<?php

namespace MainBundle\Repository;

/**
 * IndustryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndustryRepository extends \Doctrine\ORM\EntityRepository
{

	public function searchBy(String $search)
	{
		
        $qb = $this->createQueryBuilder('i');
           
        $qb->where('i.shortName LIKE :search ')->setParameter('search', '%'.$search.'%')
          ->orWhere('i.longName LIKE :search ')->setParameter('search', '%'.$search.'%')
        ;
        
        return $qb->getQuery()
                    ->getResult()
        ;
    }

}
